services:
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-kraft
    container_name: kafka-kraft
    profiles: ["dev-services", "init-services"]
    ports:
      - "9092:9092"
      - "9093:9093"
    restart: always
    #volumes:
    #  - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-kraft:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-kraft:9092,CONTROLLER://kafka-kraft:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-kraft:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  init-kafka:
    image: confluentinc/cp-kafka:latest
    profiles: ["dev-services", "init-services"]
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka-kraft:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka-kraft:9092 --create --if-not-exists --topic fleet-management-events --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka-kraft:9092 --create --if-not-exists --topic route-management-events --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka-kraft:9092 --create --if-not-exists --topic delivery-tracking-events --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka-kraft:9092 --list
      "

  mongo:
    image: mongo:latest
    container_name: mongo-container
    profiles: ["dev-services", "init-services"]
    ports:
      - 27017:27017
    restart: always
    #volumes:
    #  - mongodb_data:/data/db

  sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: sql-container
    profiles: ["dev-services", "init-services"]
    ports:
      - 1433:1433
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: $$tr0ngS@P@ssw0rd02
      MSSQL_PID: Express
    #volumes:
    #  - sqlserver_data:/var/opt/mssql

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    profiles: ["dev-services", "init-services"]
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'

  # Delivery Tracking Services
  delivery-tracking-command-api:
    build:
      context: .
      dockerfile: Eroad.DeliveryTracking.Command.API/Dockerfile
    container_name: delivery-tracking-command-api
    profiles: ["init-services"]
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport=true
      - MongoDbConfig__ConnectionString=mongodb://mongo:27017
      - MongoDbConfig__Database=deliverytracking
      - MongoDbConfig__Collection=eventStore
      - ProducerConfig__BootstrapServers=kafka-kraft:9092
      - KafkaConfig__Topic=delivery-tracking-events
    depends_on:
      - kafka
      - mongo
    restart: on-failure

  delivery-tracking-query-api:
    build:
      context: .
      dockerfile: Eroad.DeliveryTracking.Query.API/Dockerfile
    container_name: delivery-tracking-query-api
    profiles: ["init-services"]
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport=true
      - ConnectionStrings__SqlServer=Server=sql;Database=DeliveryTrackingQuery;User Id=sa;Password=$$tr0ngS@P@ssw0rd02;TrustServerCertificate=true;
      - ConsumerConfig__GroupId=delivery-query-consumer
      - ConsumerConfig__BootstrapServers=kafka-kraft:9092
      - ConsumerConfig__EnableAutoCommit=false
      - ConsumerConfig__AutoOffsetReset=Earliest
      - ConsumerConfig__AllowAutoCreateTopics=true
    depends_on:
      - kafka
      - sql
    restart: on-failure

  # Fleet Management Services
  fleet-management-command-api:
    build:
      context: .
      dockerfile: Eroad.FleetManagement.Command.API/Dockerfile
    container_name: fleet-management-command-api
    profiles: ["init-services"]
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport=true
      - MongoDbConfig__ConnectionString=mongodb://mongo:27017
      - MongoDbConfig__Database=fleetmanagement
      - MongoDbConfig__Collection=eventStore
      - ProducerConfig__BootstrapServers=kafka-kraft:9092
      - KafkaConfig__Topic=fleet-management-events
    depends_on:
      - kafka
      - mongo
    restart: on-failure

  fleet-management-query-api:
    build:
      context: .
      dockerfile: Eroad.FleetManagement.Query.API/Dockerfile
    container_name: fleet-management-query-api
    profiles: ["init-services"]
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport=true
      - ConnectionStrings__SqlServer=Server=sql;Database=FleetManagementQuery;User Id=sa;Password=$$tr0ngS@P@ssw0rd02;TrustServerCertificate=true;
      - ConsumerConfig__GroupId=fleet-query-consumer
      - ConsumerConfig__BootstrapServers=kafka-kraft:9092
      - ConsumerConfig__EnableAutoCommit=false
      - ConsumerConfig__AutoOffsetReset=Earliest
      - ConsumerConfig__AllowAutoCreateTopics=true
    depends_on:
      - kafka
      - sql
    restart: on-failure

  # Route Management Services
  route-management-command-api:
    build:
      context: .
      dockerfile: Eroad.RouteManagement.Command.API/Dockerfile
    container_name: route-management-command-api
    profiles: ["init-services"]
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport=true
      - MongoDbConfig__ConnectionString=mongodb://mongo:27017
      - MongoDbConfig__Database=routemanagement
      - MongoDbConfig__Collection=eventStore
      - ProducerConfig__BootstrapServers=kafka-kraft:9092
      - KafkaConfig__Topic=route-management-events
    depends_on:
      - kafka
      - mongo
    restart: on-failure

  route-management-query-api:
    build:
      context: .
      dockerfile: Eroad.RouteManagement.Query.API/Dockerfile
    container_name: route-management-query-api
    profiles: ["init-services"]
    ports:
      - "5006:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport=true
      - ConnectionStrings__SqlServer=Server=sql;Database=RouteManagementQuery;User Id=sa;Password=$$tr0ngS@P@ssw0rd02;TrustServerCertificate=true;
      - ConsumerConfig__GroupId=route-query-consumer
      - ConsumerConfig__BootstrapServers=kafka-kraft:9092
      - ConsumerConfig__EnableAutoCommit=false
      - ConsumerConfig__AutoOffsetReset=Earliest
      - ConsumerConfig__AllowAutoCreateTopics=true
    depends_on:
      - kafka
      - sql
    restart: on-failure

  # BFF Gateway
  bff-gateway:
    build:
      context: .
      dockerfile: Eroad.BFF.Gateway/Dockerfile
    container_name: bff-gateway
    profiles: ["init-services"]
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceEndpoints__DeliveryTrackingBaseUrl=http://delivery-tracking-query-api:8080
      - ServiceEndpoints__DeliveryTrackingCommandBaseUrl=http://delivery-tracking-command-api:8080
      - ServiceEndpoints__FleetManagementBaseUrl=http://fleet-management-query-api:8080
      - ServiceEndpoints__FleetManagementCommandBaseUrl=http://fleet-management-command-api:8080
      - ServiceEndpoints__RouteManagementBaseUrl=http://route-management-query-api:8080
      - ServiceEndpoints__RouteManagementCommandBaseUrl=http://route-management-command-api:8080
    depends_on:
      - delivery-tracking-command-api
      - delivery-tracking-query-api
      - fleet-management-command-api
      - fleet-management-query-api
      - route-management-command-api
      - route-management-query-api
    restart: on-failure
   
networks:
  default:    
    driver: bridge

volumes:
  mongodb_data: {}
  kafka_data: {}
  sqlserver_data: {}
